<?php
/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Daniel Deady
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/* @var $this Clockworkgeek_Futureslider_Block_Banner */
if (! ($children = $this->getSortedChildBlocks())) {
    // output nothing if no slides were loaded
    return;
}
$activeRules = '';
foreach ($children as $child) {
    $activeRules[] = "#radio-{$child->getHtmlId()}:checked~.{$child->getHtmlId()}";
}
$activeRules = implode(',', $activeRules);
?>
<style type="text/css">
<?php echo $activeRules ?> { z-index: 2; }
</style>
<div<?php echo $this->getHtmlAttributes()->addClass('prevnext') ?>>
<?php reset($children)->setChecked('checked="checked" ') // only first is checked ?>
<?php if (count($children) > 1) foreach ($children as $child): // inputs must occur before labels ?>
    <input type="radio" name="<?php echo $this->getHtmlId() ?>" id="radio-<?php echo $child->getHtmlId() ?>" class="no-display" hidden="hidden" <?php echo $child->getChecked() ?>/>
<?php endforeach; ?>
<?php echo $this->getChildHtml(); ?>

<?php if (count($children) > 1) foreach ($children as $child): ?>
    <label for="radio-<?php echo $child->getPrev()->getHtmlId() ?>" class="future-nav-prev <?php echo $child->getHtmlId() ?>"></label>
    <label for="radio-<?php echo $child->getNext()->getHtmlId() ?>" class="future-nav-next <?php echo $child->getHtmlId() ?>"></label>
<?php endforeach; ?>

</div>
